# Generated by Django 5.0.7 on 2025-11-23 11:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0096_remove_profil_neues_hj_frage_profil_keine_hj_frage'),
        ('core', '0119_remove_zaehler_bonus_zaehler_letzter_typ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('schwierigkeit', models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('S', 'Grundschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler/in')], default='E', max_length=1)),
                ('note_streng', models.BooleanField(default=True)),
                ('proto_marker', models.PositiveIntegerField(blank=True, help_text='Marker für Protokoll.hilfe (>=1000, eindeutig)', null=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('aktiv', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='accounts.lerngruppe')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('gruppe', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestEinstellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('typ_anf', models.SmallIntegerField(default=0)),
                ('typ_end', models.SmallIntegerField(default=0)),
                ('reihenfolge', models.JSONField(blank=True, default=list, null=True)),
                ('optionen_text', models.CharField(blank=True, default='', max_length=100, verbose_name='Optionen')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorie')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einstellungen', to='tests.test')),
            ],
            options={
                'verbose_name': 'Testeinstellung',
                'verbose_name_plural': 'Testeinstellungen',
                'ordering': ['kategorie__zeile'],
                'unique_together': {('test', 'kategorie')},
            },
        ),
    ]
