# Generated by Django 5.0.7 on 2025-11-03 13:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0096_remove_profil_neues_hj_frage_profil_keine_hj_frage'),
        ('core', '0119_remove_zaehler_bonus_zaehler_letzter_typ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('proto_marker', models.PositiveIntegerField(blank=True, help_text='Marker für Protokoll.hilfe (>=1000, eindeutig)', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lerngruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='accounts.mathegruppe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('typ_anf', models.SmallIntegerField(default=0)),
                ('typ_end', models.SmallIntegerField(default=0)),
                ('reihenfolge', models.JSONField(blank=True, default=list, null=True)),
                ('optionen_text', models.CharField(blank=True, default='', max_length=40, verbose_name='Optionen')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorie')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='tests.test')),
            ],
            options={
                'ordering': ['kategorie__zeile'],
                'unique_together': {('test', 'kategorie')},
            },
        ),
    ]
