# Generated by Django 4.0 on 2024-07-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_remove_duellant_profil'),
        ('duell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duellant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('liga', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('platz', models.SmallIntegerField(blank=True, null=True)),
                ('aufsteiger', models.BooleanField(default=False)),
                ('abwesend', models.BooleanField(default=False)),
                ('spiele', models.SmallIntegerField(default=0)),
                ('punkte', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('punkte_spiel', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('pps', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duellprofil', to='accounts.profil')),
            ],
            options={
                'verbose_name_plural': 'Duellanten',
            },
        ),
        migrations.AlterField(
            model_name='duell_protokoll',
            name='duellant_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellant_1', to='duell.duellant'),
        ),
        migrations.AlterField(
            model_name='duell_protokoll',
            name='duellant_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellant_2', to='duell.duellant'),
        ),
    ]
