# Generated by Django 4.0 on 2024-07-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0002_duellant_alter_duell_protokoll_duellant_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duell_Protokoll',
        ),
    ]
