# Generated by Django 4.0 on 2024-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0002_duellant_alter_duell_protokoll_duellant_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell_protokoll',
            name='wertung',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
