# Generated by Django 4.0 on 2024-07-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_delete_duellant'),
        ('core', '0114_delete_duell_protokoll'),
        ('duell', '0003_delete_duell_protokoll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duell_Protokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duellant_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duellant_1', to='duell.duellant')),
                ('duellant_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duellant_2', to='duell.duellant')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellgruppe', to='accounts.lerngruppe')),
                ('protokoll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duellprotokoll', to='core.protokoll')),
            ],
            options={
                'verbose_name': 'Duell_Protokoll',
                'verbose_name_plural': 'Duell_Protokolle',
            },
        ),
    ]
