# Generated by Django 4.0 on 2024-07-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0004_alter_duell_protokoll_wertung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duell_protokoll',
            name='wertung',
        ),
    ]
