# Generated by Django 5.0.7 on 2024-08-01 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_delete_duell_protokoll'),
        ('duell', '0004_duell_protokoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell_protokoll',
            name='protokoll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellprotokoll', to='core.protokoll'),
        ),
        migrations.CreateModel(
            name='Duell_Wertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingabe', models.CharField(blank=True, max_length=20)),
                ('punkte', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('duell_protokoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellwertung', to='duell.duell_protokoll')),
                ('duellant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duellant', to='duell.duellant')),
            ],
            options={
                'verbose_name': 'Duell_Wertung',
                'verbose_name_plural': 'Duell_Wertungen',
            },
        ),
    ]
