# Generated by Django 4.0 on 2024-07-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0004_duell_protokoll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duell_Wertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingabe', models.CharField(blank=True, max_length=20)),
                ('punkte', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('duell_protokoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellwertung', to='duell.duell_protokoll')),
                ('duellant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duellant', to='duell.duellant')),
            ],
            options={
                'verbose_name': 'Duell_Wertung',
                'verbose_name_plural': 'Duell_Wertungen',
            },
        ),
    ]
