# Generated by Django 5.0.7 on 2024-08-01 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0005_alter_duell_protokoll_protokoll_duell_wertung'),
    ]

    operations = [
        migrations.AddField(
            model_name='duell_wertung',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datum'),
            preserve_default=False,
        ),
    ]
