# Generated by Django 4.0 on 2024-07-26 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0005_duell_wertung'),
    ]

    operations = [
        migrations.AddField(
            model_name='duell_wertung',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 26, 11, 11, 55, 248172, tzinfo=utc), verbose_name='datum'),
            preserve_default=False,
        ),
    ]
