# Generated by Django 5.0.7 on 2024-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0006_duell_wertung_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='duell_wertung',
            name='anmerkung',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
