# Generated by Django 4.0 on 2024-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0006_duell_protokoll_wertung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell_protokoll',
            name='wertung',
            field=models.JSONField(null=True),
        ),
    ]
