# Generated by Django 4.0 on 2024-07-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0006_duell_wertung_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell_wertung',
            name='duellant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duellant', to='duell.duellant'),
        ),
    ]
