# Generated by Django 5.0.7 on 2024-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0007_duell_wertung_anmerkung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell_wertung',
            name='anmerkung',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
