# Generated by Django 4.0 on 2024-07-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_delete_duell_protokoll'),
        ('duell', '0007_alter_duell_wertung_duellant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell_protokoll',
            name='protokoll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellprotokoll', to='core.protokoll'),
        ),
    ]
