# Generated by Django 5.0.7 on 2024-08-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0008_alter_duell_wertung_anmerkung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duell_wertung',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='duell_wertung',
            name='duellant',
        ),
        migrations.RemoveField(
            model_name='duell_wertung',
            name='eingabe',
        ),
        migrations.RemoveField(
            model_name='duell_wertung',
            name='punkte',
        ),
        migrations.AddField(
            model_name='duell_wertung',
            name='duellant_nr',
            field=models.SmallIntegerField(default=0),
        ),
    ]
