# Generated by Django 5.0.7 on 2024-08-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0009_remove_duell_wertung_datum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duell_wertung',
            name='punkte',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
