# Generated by Django 5.0.7 on 2024-08-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0010_duell_wertung_punkte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duell_Wertung',
            new_name='Duell_Eingabe',
        ),
    ]
