# Generated by Django 5.0.7 on 2024-08-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0011_rename_duell_wertung_duell_eingabe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duell_eingabe',
            options={'verbose_name': 'Duell_Eingabe', 'verbose_name_plural': 'Duell_Eingaben'},
        ),
        migrations.AddField(
            model_name='duell_eingabe',
            name='eingabe',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
