# Generated by Django 5.0.7 on 2024-08-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0012_alter_duell_eingabe_options_duell_eingabe_eingabe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duellant',
            name='punkte_spiel',
        ),
    ]
