# Generated by Django 5.0.7 on 2024-08-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_remove_profil_duell_gruppe'),
        ('core', '0114_delete_duell_protokoll'),
        ('duell', '0013_remove_duellant_punkte_spiel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duell_Protokoll',
            new_name='Duell',
        ),
        migrations.AlterModelOptions(
            name='duell',
            options={'verbose_name': 'Duell', 'verbose_name_plural': 'Duelle'},
        ),
    ]
