# Generated by Django 5.0.7 on 2024-08-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0014_rename_duell_protokoll_duell_alter_duell_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duell_Protokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duellant_nr', models.SmallIntegerField(default=0)),
                ('eingabe', models.CharField(blank=True, max_length=20)),
                ('punkte', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('anmerkung', models.CharField(blank=True, default='', max_length=40)),
                ('duell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellprotokoll', to='duell.duell')),
            ],
            options={
                'verbose_name': 'Duell_Eingabe',
                'verbose_name_plural': 'Duell_Eingaben',
            },
        ),
        migrations.DeleteModel(
            name='Duell_Eingabe',
        ),
    ]
