# Generated by Django 5.0.7 on 2024-08-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0015_duell_protokoll_delete_duell_eingabe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duell_protokoll',
            options={'verbose_name': 'Duell_Protokoll', 'verbose_name_plural': 'Duell_Protokoll'},
        ),
    ]
