# Generated by Django 4.0.3 on 2024-10-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_lerngruppe_temp'),
        ('duell', '0016_alter_duell_protokoll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='duellant',
            name='gruppe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duellant', to='accounts.lerngruppe', verbose_name='Lerngruppe'),
        ),
        migrations.AlterField(
            model_name='duellant',
            name='profil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duellprofil', to='accounts.profil'),
        ),
    ]
