# Generated by Django 5.0.7 on 2025-11-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_alter_lerngruppe_lehrer_alter_profil_gruppe'),
        ('core', '0120_alter_hilfe_kategorie'),
        ('duell', '0017_duellant_gruppe_alter_duellant_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell',
            name='duellant_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duelle_als_1', related_query_name='duell_als_1', to='duell.duellant'),
        ),
        migrations.AlterField(
            model_name='duell',
            name='duellant_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duelle_als_2', related_query_name='duell_als_2', to='duell.duellant'),
        ),
        migrations.AlterField(
            model_name='duell',
            name='gruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duelle', related_query_name='duell', to='accounts.lerngruppe'),
        ),
        migrations.AlterField(
            model_name='duell',
            name='protokoll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duelle', related_query_name='duell', to='core.protokoll'),
        ),
        migrations.AlterField(
            model_name='duell_protokoll',
            name='duell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellprotokolle', related_query_name='duellprotokoll', to='duell.duell'),
        ),
        migrations.AlterField(
            model_name='duellant',
            name='gruppe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duellanten', related_query_name='duellant', to='accounts.lerngruppe', verbose_name='Lerngruppe'),
        ),
    ]
