# Generated by Django 4.0 on 2023-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_protokoll_richtig'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='abbrechen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='protokoll',
            name='falsch',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='protokoll',
                    name='hilfe',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='loesung',
            field=models.BooleanField(default=False),
        ),
    ]
