# Generated by Django 4.1.5 on 2023-02-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_protokoll_abbrechen_protokoll_falsch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protokoll',
            name='abbrechen',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='falsch',
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='hilfe',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE core_protokoll
            ALTER COLUMN loesung TYPE jsonb
            USING to_jsonb(loesung);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="protokoll",
                    name="loesung",
                    field=models.JSONField(),
                ),
            ],
        ),
    ]
