# Generated by Django 4.0 on 2023-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_rename_abbrechen_protokoll_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='help',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE core_protokoll
            ALTER COLUMN hilfe TYPE smallint
            USING (CASE WHEN hilfe THEN 1 ELSE 0 END);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="protokoll",
                    name="hilfe",
                    field=models.SmallIntegerField(...),  # exakt wie 0086 es will
                ),
            ],
        ),
    ]