# Generated by Django 4.0 on 2023-02-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_protokoll_help_alter_protokoll_hilfe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='tries',
            new_name='versuche',
        ),
        migrations.RenameField(
            model_name='protokoll',
            old_name='value',
            new_name='wert',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='help',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='szeit',
        ),
        migrations.AddField(
            model_name='protokoll',
            name='hilfe_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE core_protokoll
            ALTER COLUMN hilfe TYPE boolean
            USING (hilfe <> 0);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="protokoll",
                    name="hilfe",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
