# Generated by Django 4.0 on 2024-07-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_duellant_liga'),
        ('core', '0101_alter_protokoll_titel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duell_Protokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkte_1', models.SmallIntegerField(default=0)),
                ('punkte_2', models.SmallIntegerField(default=0)),
                ('duellant_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duellant_1', to='accounts.duellant')),
                ('duellant_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duellant_2', to='accounts.duellant')),
                ('gruppe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duellgruppe', to='accounts.lerngruppe')),
                ('protokoll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duellprotokoll', to='core.protokoll')),
            ],
        ),
    ]
