# Generated by Django 4.0 on 2024-07-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_duell_protokoll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duell_protokoll',
            options={'verbose_name': 'Duell_Protokoll', 'verbose_name_plural': 'Duell_Protokolle'},
        ),
        migrations.AlterModelOptions(
            name='protokoll',
            options={'verbose_name': 'Protokoll', 'verbose_name_plural': 'Protokolle'},
        ),
    ]
