# Generated by Django 4.0 on 2024-07-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_duell_protokoll_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell_protokoll',
            name='punkte_1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='duell_protokoll',
            name='punkte_2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
