# Generated by Django 4.0 on 2024-07-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_duell_protokoll_punkte_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duell_protokoll',
            name='punkte_1',
        ),
        migrations.RemoveField(
            model_name='duell_protokoll',
            name='punkte_2',
        ),
        migrations.AlterField(
            model_name='duell_protokoll',
            name='protokoll',
            field=models.TextField(blank=True, null=True),
        ),
    ]
