# Generated by Django 4.0 on 2024-07-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_duellant_liga'),
        ('core', '0105_remove_duell_protokoll_punkte_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duell_protokoll',
            name='gruppe',
        ),
        migrations.AddField(
            model_name='duell_protokoll',
            name='gruppe',
            field=models.ManyToManyField(related_name='duellgruppe', to='accounts.Lerngruppe'),
        ),
    ]
