# Generated by Django 4.0 on 2024-07-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_duellant_liga'),
        ('core', '0106_remove_duell_protokoll_gruppe_duell_protokoll_gruppe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell_protokoll',
            name='duellant_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellant_1', to='accounts.duellant'),
        ),
        migrations.AlterField(
            model_name='duell_protokoll',
            name='duellant_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellant_2', to='accounts.duellant'),
        ),
    ]
