# Generated by Django 4.0 on 2024-07-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_duell_protokoll_duellant_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duell_Protokoll',
        ),
    ]
