# Generated by Django 4.0 on 2024-07-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_duell_protokoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='duell_protokoll',
            name='wertung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duell_protokoll',
            name='protokoll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellprotokoll', to='core.protokoll'),
        ),
    ]
