# Generated by Django 4.0 on 2024-07-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_duell_protokoll_wertung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duell_protokoll',
            name='wertung',
        ),
        migrations.AlterField(
            model_name='duell_protokoll',
            name='protokoll',
            field=models.TextField(blank=True, null=True),
        ),
    ]
