# Generated by Django 4.0 on 2024-07-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_remove_duell_protokoll_wertung_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duell_Protokoll',
        ),
    ]
