# Generated by Django 4.0 on 2024-07-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_duellant_liga'),
        ('core', '0112_delete_duell_protokoll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duell_Protokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wertung', models.TextField(blank=True, null=True)),
                ('duellant_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellant_1', to='accounts.duellant')),
                ('duellant_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellant_2', to='accounts.duellant')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellgruppe', to='accounts.lerngruppe')),
                ('protokoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duellprotokoll', to='core.protokoll')),
            ],
            options={
                'verbose_name': 'Duell_Protokoll',
                'verbose_name_plural': 'Duell_Protokolle',
            },
        ),
    ]
