# Generated by Django 4.0 on 2024-07-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_duell_protokoll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duell_Protokoll',
        ),
    ]
