# Generated by Django 4.0.3 on 2024-09-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_delete_duell_protokoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='bonus',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
