# Generated by Django 4.0.3 on 2024-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_zaehler_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
