# Generated by Django 5.0.7 on 2024-11-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_rename_username_geloescht_benutzername_and_more'),
        ('core', '0116_alter_zaehler_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='user',
            new_name='profil',
        ),
        migrations.RenameField(
            model_name='zaehler',
            old_name='user',
            new_name='profil',
        ),
        migrations.AlterUniqueTogether(
            name='zaehler',
            unique_together={('kategorie', 'profil')},
        ),
    ]
