# Generated by Django 5.0.7 on 2025-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_rename_user_protokoll_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='eof',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Eingaben ohne Fehler'),
        ),
    ]
