# Generated by Django 5.0.7 on 2025-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_alter_kategorie_eof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaehler',
            name='bonus',
        ),
        migrations.AddField(
            model_name='zaehler',
            name='letzter_typ',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zaehler',
            name='reihenfolge',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
