# Generated by Django 5.0.7 on 2025-11-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_remove_zaehler_bonus_zaehler_letzter_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilfe',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hilfen', related_query_name='hilfe', to='core.kategorie'),
        ),
    ]
