# Generated by Django 5.0.7 on 2025-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_alter_hilfe_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='korrigiert',
            field=models.BooleanField(default=False),
        ),
    ]
