# Generated by Django 4.0.1 on 2025-12-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_protokoll_korrigiert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='eingabe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
