# Generated by Django 4.0.1 on 2025-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_alter_protokoll_eingabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='wert',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True, verbose_name='Wert'),
        ),
    ]
