# Generated by Django 4.0.1 on 2025-12-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_alter_protokoll_wert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='titel',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
