# Generated by Django 4.0.1 on 2025-12-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_alter_protokoll_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
