# Generated by Django 4.0.1 on 2025-12-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_alter_protokoll_anmerkung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='einheit',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='frage',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
