# Generated by Django 4.0.1 on 2025-12-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_alter_protokoll_einheit_alter_protokoll_frage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
