# Generated by Django 4.0.1 on 2025-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_alter_protokoll_anmerkung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
