# Generated by Django 4.0.1 on 2025-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_alter_protokoll_anmerkung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='optionen_text',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Optionen'),
        ),
    ]
