# Generated by Django 4.0.1 on 2025-12-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_alter_zaehler_optionen_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaehler',
            name='optionen_text',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Optionen'),
        ),
    ]
