# Generated by Django 4.0.1 on 2025-12-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_alter_zaehler_optionen_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='wertung',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
