# Generated by Django 4.0.1 on 2025-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_protokoll_wertung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protokoll',
            options={},
        ),
        migrations.AddIndex(
            model_name='protokoll',
            index=models.Index(fields=['profil', 'sj', 'hj', 'kategorie'], name='prot_p_sj_hj_kat'),
        ),
        migrations.AddIndex(
            model_name='protokoll',
            index=models.Index(fields=['profil', 'start'], name='prot_p_start'),
        ),
        migrations.AddIndex(
            model_name='protokoll',
            index=models.Index(fields=['profil', 'kategorie', 'start'], name='prot_p_kat_start'),
        ),
    ]
