# Generated by Django 4.0.1 on 2026-03-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_alter_protokoll_options_protokoll_prot_p_sj_hj_kat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'ordering': ['zeile', 'pk'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='protokoll',
            options={'verbose_name': 'Protokoll', 'verbose_name_plural': 'Protokolle'},
        ),
    ]
