# Generated by Django 5.0.7 on 2026-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_alter_kategorie_options_alter_protokoll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='geloeschte_aufgaben',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
