# Generated by Django 5.0.7 on 2026-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_zaehler_geloeschte_aufgaben'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaehler',
            name='geloeschte_fehler',
            field=models.IntegerField(default=0),
        ),
    ]
