# Generated by Django 4.0.1 on 2026-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_zaehler_geloeschte_fehler'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorie',
            name='geloeschte_aufgaben',
            field=models.IntegerField(default=0),
        ),
    ]
