# Generated by Django 5.0.7 on 2026-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_kategorie_geloeschte_aufgaben'),
    ]

    operations = [
        migrations.CreateModel(
            name='EwigeBestenliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lehrer', models.CharField(max_length=100)),
                ('schule', models.CharField(max_length=100)),
                ('punkte', models.IntegerField(default=0)),
                ('letztes_datum', models.DateField()),
            ],
        ),
    ]
