# Generated by Django 4.0 on 2023-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_rename_lerngruppe_profil_gruppe'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="profil",
                    name="voreinst",
                    field=models.JSONField(),  # genau wie in 0043 vorgesehen (mit Optionen falls vorhanden)
                ),
            ],
        ),
    ]
