# Generated by Django 4.0 on 2023-01-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_profil_voreinst'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='profil',
                    name='voreinst',
                    field=models.JSONField(default=dict),
                ),
            ],
        ),
    ]
