# Generated by Django 4.0 on 2023-01-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_profil_voreinst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gruppe', to='accounts.lerngruppe'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='profil',
                    name='voreinst',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
    ]
