# Generated by Django 4.0 on 2024-03-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_profil_kurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lerngruppe',
            old_name='ab',
            new_name='erstellt_am',
        ),
    ]
