# Generated by Django 4.0 on 2024-07-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_rename_ab_lerngruppe_erstellt_am'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.SmallIntegerField(default=1)),
                ('platz', models.SmallIntegerField(blank=True)),
                ('aufsteiger', models.BooleanField(blank=True)),
                ('krank', models.BooleanField(blank=True)),
                ('punkte', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('spiele', models.SmallIntegerField(default=0)),
                ('pps', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('gruppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duellgruppe', to='accounts.lerngruppe')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duellprofil', to='accounts.profil')),
            ],
        ),
    ]
