# Generated by Django 4.0 on 2024-07-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_duell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell',
            name='platz',
            field=models.SmallIntegerField(null=True),
        ),
    ]
