# Generated by Django 4.0 on 2024-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_duell_platz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell',
            name='aufsteiger',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='duell',
            name='krank',
            field=models.BooleanField(null=True),
        ),
    ]
