# Generated by Django 4.0 on 2024-07-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_alter_duell_aufsteiger_alter_duell_krank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duell',
            options={'verbose_name_plural': 'Duell'},
        ),
        migrations.AlterField(
            model_name='duell',
            name='aufsteiger',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='duell',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duellgruppe', to='accounts.lerngruppe'),
        ),
        migrations.AlterField(
            model_name='duell',
            name='krank',
            field=models.BooleanField(default=False),
        ),
    ]
