# Generated by Django 4.0 on 2024-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_alter_duell_options_alter_duell_aufsteiger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duell',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
