# Generated by Django 4.0 on 2024-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_duell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell',
            name='platz',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
