# Generated by Django 4.0 on 2024-07-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_duell_platz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duell',
            name='liga',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
