# Generated by Django 4.0 on 2024-07-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_duell_liga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duell',
            old_name='krank',
            new_name='abwesend',
        ),
    ]
