# Generated by Django 4.0 on 2024-07-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_rename_krank_duell_abwesend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duell',
            name='name',
        ),
    ]
