# Generated by Django 4.0 on 2024-07-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_remove_duell_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duell',
            new_name='Duellant',
        ),
        migrations.AlterModelOptions(
            name='duellant',
            options={'verbose_name_plural': 'Duellanten'},
        ),
    ]
