# Generated by Django 4.0 on 2024-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_rename_duell_duellant_alter_duellant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='duell',
            field=models.BooleanField(default=False),
        ),
    ]
