# Generated by Django 4.0 on 2024-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_profil_duell'),
    ]

    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.AlterField(
                model_name='profil',
                name='duell',
                field=models.PositiveSmallIntegerField(default=0),
            ),
        ],
    ),
