# Generated by Django 4.0 on 2024-07-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_profil_duell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='duell',
            new_name='duell_gruppe',
        ),
    ]
