# Generated by Django 4.0 on 2024-07-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_rename_duell_profil_duell_gruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='duellant',
            name='punkte_spiel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
