# Generated by Django 4.0 on 2024-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_duellant_punkte_spiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='duellant',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
