# Generated by Django 4.0 on 2024-07-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_duellant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duellant',
            name='gruppe',
        ),
    ]
