# Generated by Django 4.0 on 2024-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_remove_duellant_gruppe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duellant',
            name='liga',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
    ]
