# Generated by Django 4.0 on 2024-07-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_duellant_liga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duellant',
            name='profil',
        ),
    ]
