# Generated by Django 4.0 on 2024-07-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duell', '0002_duellant_alter_duell_protokoll_duellant_1_and_more'),
        ('accounts', '0080_remove_duellant_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duellant',
        ),
    ]
