# Generated by Django 4.0 on 2024-07-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_delete_duellant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='duell_gruppe',
        ),
    ]
