# Generated by Django 4.0.3 on 2024-10-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_remove_profil_duell_gruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='lerngruppe',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
