# Generated by Django 4.0.3 on 2024-10-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_lerngruppe_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lerngruppe',
            name='liga',
            field=models.BooleanField(default=True),
        ),
    ]
