# Generated by Django 5.0.7 on 2024-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_lerngruppe_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='geloescht',
            name='username',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
