# Generated by Django 5.0.7 on 2024-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_geloescht_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geloescht',
            name='username',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
