# Generated by Django 5.0.7 on 2024-11-04 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_alter_geloescht_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='geloescht',
            old_name='username',
            new_name='benutzername',
        ),
        migrations.AlterField(
            model_name='geloescht',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geloescht', to=settings.AUTH_USER_MODEL),
        ),
    ]
