# Generated by Django 5.0.7 on 2025-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_rename_username_geloescht_benutzername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='halbjahr_ab',
            field=models.DateTimeField(null=True),
        ),
    ]
