# Generated by Django 5.0.7 on 2025-01-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_profil_halbjahr_ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='alle_zeigen',
            field=models.BooleanField(default=False),
        ),
    ]
