# Generated by Django 5.0.7 on 2025-02-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_profil_alle_zeigen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geloescht',
            name='user',
        ),
    ]
