# Generated by Django 5.0.7 on 2025-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_remove_geloescht_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='alle_zeigen',
        ),
        migrations.AddField(
            model_name='profil',
            name='schuljahr_ab',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='halbjahr_ab',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
