# Generated by Django 5.0.7 on 2025-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_remove_profil_alle_zeigen_profil_schuljahr_ab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='voreinst',
        ),
        migrations.AddField(
            model_name='profil',
            name='neues_hj_frage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='neues_hj_frage_datum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
