# Generated by Django 5.0.7 on 2025-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_remove_profil_voreinst_profil_neues_hj_frage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='neues_hj_frage',
            field=models.BooleanField(default=True),
        ),
    ]
