# Generated by Django 5.0.7 on 2025-10-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_alter_profil_neues_hj_frage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='neues_hj_frage_datum',
        ),
    ]
