# Generated by Django 5.0.7 on 2025-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_remove_profil_neues_hj_frage_datum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='neues_hj_frage',
        ),
        migrations.AddField(
            model_name='profil',
            name='keine_hj_frage',
            field=models.BooleanField(default=False),
        ),
    ]
