# Generated by Django 5.0.7 on 2025-11-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_remove_profil_neues_hj_frage_profil_keine_hj_frage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lerngruppe',
            name='lehrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lerngruppen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='accounts.lerngruppe'),
        ),
    ]
