# Generated by Django 5.0.7 on 2025-11-25 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_alter_lerngruppe_lehrer_alter_profil_gruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='geloescht',
            name='erstellt_am',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
