# Generated by Django 5.0.7 on 2025-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_geloescht_erstellt_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='geloescht',
            name='grund',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
