# Generated by Django 5.0.7 on 2025-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_geloescht_grund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='kurs',
            field=models.CharField(choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('S', 'Grundschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler/in'), ('Z', 'Ausbildung/Berufsschule')], default='E', max_length=1),
        ),
    ]
