# Generated by Django 4.0.1 on 2025-12-27 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_alter_profil_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ort',
            name='plz',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
