# Generated by Django 4.0.1 on 2025-12-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_alter_ort_plz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ort',
            name='plz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
