# Generated by Django 4.0.1 on 2025-12-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_alter_ort_plz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geloescht',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
