# Generated by Django 4.0.1 on 2025-12-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_alter_geloescht_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geloescht',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
