# Generated by Django 4.0.1 on 2025-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_alter_geloescht_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geloescht',
            name='grund',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
