# Generated by Django 4.0.1 on 2025-12-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_alter_geloescht_grund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geloescht',
            name='benutzername',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
