# Generated by Django 4.0.1 on 2025-12-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_alter_geloescht_benutzername'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={},
        ),
        migrations.AddIndex(
            model_name='profil',
            index=models.Index(fields=['gruppe'], name='profil_gruppe'),
        ),
    ]
