# Generated by Django 4.0.1 on 2026-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_alter_profil_options_profil_profil_gruppe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterField(
            model_name='geloescht',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
