# Generated by Django 4.0.1 on 2026-05-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_alter_profil_options_alter_geloescht_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lerngruppe',
            name='alle_aufgaben',
            field=models.BooleanField(default=False),
        ),
    ]
