# Generated by Django 5.0.7 on 2026-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_lerngruppe_alle_aufgaben'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='sso_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schule',
            name='dienststellen_nr',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lerngruppe',
            name='alle_aufgaben',
            field=models.BooleanField(default=False, help_text='Alle Aufgaben können gerechnet werden – z.B. für das Üben für einen Test.', verbose_name='Alle Aufgaben'),
        ),
    ]
