# Generated by Django 5.0.7 on 2026-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_profil_sso_id_schule_dienststellen_nr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='sso_id',
            new_name='eduplaces_uid',
        ),
        migrations.AddField(
            model_name='profil',
            name='moodle_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
