# Generated by Django 5.0.7 on 2026-06-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_rename_sso_id_profil_eduplaces_uid_profil_moodle_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExterneSchnittstelleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schulname', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('moodle', 'SchulMoodle (LTI)'), ('eduplaces', 'EduPlaces Integration')], default='moodle', max_length=20)),
                ('consumer_key', models.CharField(help_text='Der Key/ID für die Authentifizierung (z.B. rechentrainer_schule_6072 oder eduplaces_client_id)', max_length=100, unique=True)),
                ('shared_secret', models.CharField(help_text='Das geheime Passwort (Secret) für die digitale Signatur', max_length=256)),
                ('schule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externe_konfigurationen', to='accounts.schule')),
            ],
            options={
                'verbose_name': 'Externe Schnittstellen-Konfiguration',
                'verbose_name_plural': 'Externe Schnittstellen-Konfigurationen',
            },
        ),
    ]
