# Generated by Django 5.0.7 on 2026-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_externeschnittstelleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='historische_aufgaben_falsch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profil',
            name='historische_aufgaben_richtig',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
