# Generated by Django 4.0.1 on 2026-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_profil_historische_aufgaben_falsch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EwigeBestenliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lehrer', models.CharField(max_length=100)),
                ('schule', models.CharField(max_length=100)),
                ('punkte', models.IntegerField(default=0)),
                ('letztes_datum', models.DateField()),
            ],
            options={
                'ordering': ['-punkte'],
            },
        ),
        migrations.AddIndex(
            model_name='ewigebestenliste',
            index=models.Index(fields=['punkte'], name='accounts_ew_punkte_3e2598_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ewigebestenliste',
            unique_together={('name', 'lehrer', 'schule')},
        ),
    ]
