# Generated by Django 4.0.1 on 2026-07-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_ewigebestenliste_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ewigebestenliste',
            options={'ordering': ['-punkte'], 'verbose_name': 'Ewige Bestenliste', 'verbose_name_plural': 'Ewige Bestenliste'},
        ),
    ]
