# Generated by Django 4.0.1 on 2026-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_alter_ewigebestenliste_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewigebestenliste',
            name='profil_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
