# Generated by Django 5.0.7 on 2026-07-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_ewigebestenliste_profil_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('quelle', models.CharField(default='moodle', max_length=50)),
                ('consumer_key', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rohdaten', models.TextField()),
            ],
        ),
    ]
