# Generated by Django 5.0.7 on 2026-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='rolle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
