# Generated by Django 5.0.7 on 2026-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_loginlog_rolle_loginlog_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schule',
            name='shared_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schule',
            name='dienststellen_nr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
