# Generated by Django 5.0.7 on 2026-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_schule_shared_secret_alter_schule_dienststellen_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schule',
            name='dienststellen_nr',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
