# Generated by Django 5.0.7 on 2026-07-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_alter_schule_dienststellen_nr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExterneSchnittstelleConfig',
        ),
    ]
