# Generated by Django 5.0.7 on 2026-07-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_alter_schule_dienststellen_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schule',
            name='consumer_key',
        ),
    ]
