# Generated by Django 5.0.7 on 2026-07-28 15:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_delete_externeschnittstelleconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='hj',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='jg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='katmax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='kurs',
            field=models.CharField(blank=True, choices=[('Y', 'Gymnasium'), ('R', 'Realschule'), ('H', 'Hauptschule'), ('S', 'Grundschule'), ('E', 'E-Kurs'), ('G', 'G-Kurs'), ('A', 'A-Kurs'), ('B', 'B-Kurs'), ('C', 'C-Kurs'), ('i', 'Förderschüler/in'), ('Z', 'Ausbildung/Berufsschule')], default='E', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sj',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='stufe',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.CreateModel(
            name='Physikgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('erstellt_am', models.DateField(auto_now_add=True)),
                ('lehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physikgruppen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Physikgruppen',
                'unique_together': {('lehrer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='physikgruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='accounts.physikgruppe'),
        ),
    ]
