# Generated by Django 5.0.7 on 2026-07-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0122_alter_profil_hj_alter_profil_jg_alter_profil_katmax_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EwigeBestenliste',
        ),
    ]
