# Generated by Django 5.0.7 on 2026-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_delete_ewigebestenliste'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ist_mathe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='ist_physik',
            field=models.BooleanField(default=False),
        ),
    ]
