# Generated by Django 5.0.7 on 2026-07-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0124_profil_ist_mathe_profil_ist_physik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='ist_mathe',
            new_name='mathe',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='ist_physik',
            new_name='physik',
        ),
    ]
