# Generated by Django 4.0.1 on 2026-10-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0125_rename_ist_mathe_profil_mathe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lerngruppe',
            name='eduplaces_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
