# Generated by Django 4.0.1 on 2026-07-27 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import physik.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfd_nr', models.CharField(max_length=10, unique=True, verbose_name='lfd_Nr')),
                ('schwierigkeit', models.PositiveSmallIntegerField(choices=[(1, 'Einfach'), (2, 'Mittel'), (3, 'Profi')], default=1)),
                ('typ', models.CharField(max_length=20, verbose_name='Typ')),
                ('zeichen', models.CharField(blank=True, help_text='Optional – wird vor dem Eingabefeld angezeigt (z.B. F=, R=, l=...).', max_length=10, verbose_name='Formelzeichen')),
                ('frage', models.CharField(max_length=255, verbose_name='Frage')),
                ('einheit', models.CharField(blank=True, help_text='Optional – wird hinter dem Eingabefeld angezeigt (z.B. cm, kg, °C).', max_length=10, verbose_name='Einheit')),
                ('loesung', models.CharField(blank=True, help_text='Hier steht die offizielle Antwort.', max_length=255, verbose_name='Antwort')),
                ('anmerkung', models.CharField(blank=True, help_text='Optional, nur wenn gewünscht.', max_length=255, verbose_name='Anmerkung')),
                ('erklaerung', models.TextField(blank=True, help_text='Optional. Wird angezeigt, wenn auf »Lösung« geklickt wird oder eine falsche Eingabe gemacht wurde.', verbose_name='Erklärung')),
                ('hilfe', models.CharField(blank=True, help_text='Optional, nur wenn gewünscht.', max_length=255, verbose_name='Hilfe')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
            },
        ),
        migrations.CreateModel(
            name='ThemenBereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordnung', models.PositiveSmallIntegerField(unique=True)),
                ('kurz', models.CharField(blank=True, default='', max_length=2)),
                ('thema', models.CharField(max_length=30)),
                ('kapitel_unabhaengig', models.BooleanField(default=False, verbose_name='Kapitel unabhängig')),
                ('farbe', models.CharField(max_length=40)),
                ('eingeblendet', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Themenbereich',
                'verbose_name_plural': 'Themenbereiche',
                'ordering': ['ordnung'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physik_einstellungen', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physik_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kapitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeile', models.PositiveSmallIntegerField()),
                ('kapitel', models.CharField(max_length=100)),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapitel', to='physik.themenbereich')),
            ],
            options={
                'verbose_name': 'Kapitel',
                'verbose_name_plural': 'Kapitel',
                'ordering': ['thema__ordnung', 'zeile'],
            },
        ),
        migrations.CreateModel(
            name='FehlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingegebene_antwort', models.TextField()),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fehler_logs', to='physik.aufgabe')),
            ],
            options={
                'ordering': ['-zeitpunkt'],
            },
        ),
        migrations.CreateModel(
            name='AufgabeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionen', to='physik.aufgabe')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Optionen',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='AufgabeBild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bild', models.ImageField(blank=True, null=True, upload_to=physik.models.bild_pfad)),
                ('video', models.FileField(blank=True, null=True, upload_to=physik.models.bild_pfad)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='physik.aufgabe')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='kapitel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='physik.kapitel'),
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='thema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='physik.themenbereich'),
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_aufgaben', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Protokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach', models.IntegerField(default=2)),
                ('letzte_bearbeitung', models.DateTimeField(auto_now=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physik.aufgabe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lernkärtchen-Protokoll',
                'verbose_name_plural': 'Lernkärtchen-Protokolle',
                'unique_together': {('user', 'aufgabe')},
            },
        ),
        migrations.AddConstraint(
            model_name='kapitel',
            constraint=models.UniqueConstraint(fields=('thema', 'zeile'), name='uniq_kapitel_pro_thema_zeile'),
        ),
        migrations.AlterUniqueTogether(
            name='aufgabeoption',
            unique_together={('aufgabe', 'position')},
        ),
    ]
