# Generated by Django 4.0.1 on 2026-07-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
